---
# Default cloud provider (can be overridden)
cloud_provider: "aws"  # Options: "aws", "gcp"
aws_region: "{{ lookup('env', 'AWS_REGION') | default('eu-central-1') }}"

config_path: "../config-kuber.json"
env: "production"
# Container registry URLs
registry_urls:
  aws: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
  gcp: "gcr.io/{{ gcp_project_id }}"
  dockerhub: "docker.io"

# Default AWS settings
aws_account_id: "253490768279"  # Replace with actual account ID

# Default GCP settings
gcp_project_id: "my-project"  # Replace with actual project ID

#For group k3s

k3s_group: "k3s_node"
tls_san: "{{ hostvars[groups[k3s_group][0]].ansible_host }}"
master_node: "{{ groups[k3s_group][0] }}"
master_ip: "{{ hostvars[master_node].ansible_host }}"

# List of domain names included in the certificate and ingress
cert_domains:
  - "qjsoq.pp.ua"

domain_jenkins:
  - "jenkins.qjsoq.pp.ua"

ingress_domains:
  - "qjsoq.pp.ua"
