- name: Install Google Cloud Ops Agent
  hosts: all   # or specify your GCP hosts group
  become: yes
  roles:
    - gcp-ops-agent

- name: Configure reverse proxy
  hosts: reverse-proxy
  become: yes
  roles:
    - reverse_proxy

- name: Deploy Redis Service
  hosts: redis
  become: yes
  vars_files:
    - "{{ config_path }}"
  roles:
    - role: install_packages
    - role: container_exec
  vars:
    container: "{{ containers.redis }}"

- name: Deploy Backend Service
  hosts: backend
  become: yes
  vars_files:
    - "{{ config_path }}"
  roles:
    - role: install_packages
    - role: awscli
    - role: ecr_docker_auth
    - role: container_exec
  vars:
    container: "{{ containers.backend }}"

- name: Deploy Frontend Service
  hosts: frontend
  become: yes
  vars_files:
    - "{{ config_path }}"
  roles:
    - role: install_packages
    - role: awscli
    - role: ecr_docker_auth
    - role: container_exec
  vars:
    container: "{{ containers.frontend }}"

- name: K3s cluster join
  hosts: public
  become: yes
  roles: 
    - k3s_cluster_join


