# - name: Install Python dependencies
#   ansible.builtin.apt:
#     update_cache: yes
#     pkg:
#       - python3-pip
#     state: present

# - name: Install Python packages system-wide (PEP 668 override)
#   ansible.builtin.pip:
#     name:
#       - openshift
#       - pyyaml
#       - kubernetes
#     extra_args: --break-system-packages
#     executable: pip3

- name: Debug full db_secret_result
  debug:
    var: db_secret_result

- name: Debug decoded secrets
  debug:
    msg: |
      Decoded Secrets:
      -----------------
      DB User: {{ db_user }}
      DB Password: {{ db_password }}
      DB Name: {{ db_name }}
      DB Host: {{ db_host }}
      DB Port: {{ db_port }}
      GKE Ingress IP: {{ gke_ingress_ip }}
      
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ item.name }}"
    api_version: v1
    kind: Namespace
    state: present
  loop: "{{ namespaces }}"
  tags: namespaces

- name: Deploy ConfigMap
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/configmap.yaml.j2"
  loop: "{{ configmaps }}"
  tags:
    - configmap


- name: Deploy Secret
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/secret.yaml.j2"
  loop: "{{ secrets }}"
  tags:
    - secret


- name: Deploy Service
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/service.yaml.j2"
  loop: "{{ services }}"
  tags:
    - service


- name: Deploy Deployment
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/deployment.yaml.j2"
  loop: "{{ deployments }}"
  tags:
    - deployment

- name: Apply Ingress
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/app-ingress.yaml.j2"
  loop: "{{ ingress }}"
  tags:
    - ingress

- name: Apply Cert
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/app-certificate.yaml.j2"
    namespace: "{{ namespace | default('app-ingress') }}"
  loop: "{{ ingress }}"
  tags:
    - cert
