# SPDX-License-Identifier: MIT-0
---
# tasks file for restore-db-from-dump

- name: Restore PostgreSQL database to Cloud SQL from local dump
  delegate_to: localhost
  ansible.builtin.command: >
    psql --set ON_ERROR_STOP=off
         -U {{ db_user }}
         -h {{ db_host }}
         -p {{ db_port | default('5432') }}
         -d {{ db_name }}
         -1 -f {{ db_dump_file }}
  environment:
    PGPASSWORD: "{{ db_password }}"
