---
- name: Include task install Helm
  ansible.builtin.include_tasks:
    file: install_helm.yml

- name: Add cert-manager Helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install cert-manager with Helm
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    create_namespace: true
    values:
      installCRDs: true
      webhook:
        timeoutSeconds: 30
    wait: true
    wait_timeout: 600s

- name: "Create ClusterIssuer"
  import_tasks: create_cluster_issuer.yml

- name: "Deploy Certificate"
  import_tasks: create_certificate.yml
